remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title: "About me"

author:
  name: "Javier de la Fuente Cedeño"
  avatar: "/assets/images/profile.jpeg" # Ensure your image is correctly uploaded
  bio: "Business Development & Project Management"
  location: "Pamplona, Spain"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/javier-de-la-fuente-cedeño/"



defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# Sidebar settings
author_profile: true

assets:
  css: 
    - "assets/css/main.scss"

include:
  - _pages

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed

header_scripts:
  - "<link rel='icon' href='assets/images/favicon.ico' type='image/x-icon'>"